version: "3"
services:
  master:
    build: .
    image: spark-demo:latest
    ports:
      - "8080:8080"
      - "7077:7077"
  slave_1:
    image: spark-demo:latest
    entrypoint: /apps/spark_demo/spark/sbin/start-slave.sh -c 1 -m 512M spark://master:7077
    depends_on:
      - master
      - wiremock
  slave_2:
    image: spark-demo:latest
    entrypoint: /apps/spark_demo/spark/sbin/start-slave.sh -c 1 -m 512M spark://master:7077
    depends_on:
      - master
      - wiremock
  slave_3:
    image: spark-demo:latest
    entrypoint: /apps/spark_demo/spark/sbin/start-slave.sh -c 1 -m 512M spark://master:7077
    depends_on:
      - master
      - wiremock
  wiremock:
    image: rodolpheche/wiremock:latest
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: --verbose --local-response-templating
  driver:
    build: 
      context: .
      dockerfile: Dockerfile_Driver
    image: spark-demo-driver:latest
    depends_on:
      - master
      - wiremock
